### ISSUE TITLE
Google terms/Only show up if guest(access)

### ISSUE THREAD

**Issue by wehowski** [GreenMeteor/adsense#5]
Hello,
it's me again:

Google was not validating my humhub site: https://support.google.com/adsense/answer/10502938?hl=de&visit_id=637691096271317556-3796207143&rd=2

I guess one reason could be the mod is showing ads to guest users even if he visits account-protected contents (which results in no dublicate or "bad" content from the point of google).

I suggest following modification (maybe you can add a more configurable option "Show ads to guests on login-pages...?" or similar!?

_\humhub\modules\adsense\Event_ 
````php
    public static function addAdFrame($event)
    {		
	if(\Yii::$app->user->isGuest && \humhub\modules\user\helpers\AuthHelper::isGuestAccessEnabled()){
                $event->sender->addWidget(widgets\AdFrame::class, [], ['sortOrder' => Yii::$app->getModule('adsense')->settings->get('sort')]);
        }
    }`

regards,
Till

Off-Topic feature request: Only show ads if user confirms to cookie-consent-banner?

**Comment by ArchBlood** [comment]
Hello @wehowski, hope you're having a good evening, after reviewing your concerns for guest access, I would like to advise you that the snippet of code you've provided only makes the module work for guests not users of the site, so we can not add such a function. The reason why it only works for guests is that there is an `if` statement that only implements the guest-viewable, there are no `else` or `elseif` statements for the user, adding the `&&` statement is completely ignored in the `if` statement, you should use `==` instead.

If you want to allow guests to view the widget panel then add the following snippet to the Events.php

```php
    public static function addAdFrame($event)
    {
        if (\Yii::$app->user->isGuest){
        }
        $event->sender->addWidget(widgets\AdFrame::class, [], ['sortOrder' => Yii::$app->getModule('adsense')->settings->get('sort')]);
    }
```
Doing this will not only show the widget panel to the user but also the guest, making it fully global.

You could also do something like the following as well and it should return the same value.

```php
    public static function addAdFrame($event)
    {
        if (\Yii::$app->user->isGuest && \humhub\modules\user\helpers\AuthHelper::isGuestAccessEnabled()){
        }
        $event->sender->addWidget(widgets\AdFrame::class, [], ['sortOrder' => Yii::$app->getModule('adsense')->settings->get('sort')]);
    }
```
The reason the second option works is because there are no return values given in the `if` statement, in turn, works the same as the first method.

Overall the first method is more recommended for the lightweight feel.

But sadly it was removed here it seems https://github.com/GreenMeteor/adsense/commit/54a7c10eb7ea31e93329f8f6cfc086f313570576 but I can't be sure why, I will have to ask the team about this. 🤔

**Comment by wehowski** [comment]
Hello,
just for completeness, I would like to add, that my version works in conjunction with the consent module, to keep compliance to EU law.
My Event.php now looks like 
```PHP
  public static function addAdFrame($event)
    {
        if ( 
			Yii::$app->user->isGuest && 
			AuthHelper::isGuestAccessEnabled() &&
			isset($_COOKIE['cookieconsent_status']) && 'dismiss' === $_COOKIE['cookieconsent_status']
		   )
        {
            $event->sender->addWidget(widgets\AdFrame::class, [], ['sortOrder' => Yii::$app->getModule('adsense')->settings->get('sort')]);

        }
    }
```

**Comment by ArchBlood** [comment]
> Hello,
> just for completeness, I would like to add, that my version works in conjunction with the consent module, to keep compliance to EU law.
> My Event.php now looks like 
> ```PHP
>   public static function addAdFrame($event)
>     {
>         if ( 
> 			Yii::$app->user->isGuest && 
> 			AuthHelper::isGuestAccessEnabled() &&
> 			isset($_COOKIE['cookieconsent_status']) && 'dismiss' === $_COOKIE['cookieconsent_status']
> 		   )
>         {
>             $event->sender->addWidget(widgets\AdFrame::class, [], ['sortOrder' => Yii::$app->getModule('adsense')->settings->get('sort')]);
> 
>         }
>     }
> ```

Could you create a P/R and will discuss it more from there, and if needed extend it to better fit all users of the module?

**Comment by wehowski** [comment]
Hello ArchBlood,
I made a pull request.
(Hope its OK, I am not used to pull requests to other orgs/repos)
regards,
Till

**Comment by ArchBlood** [comment]
> Hello ArchBlood,
> I made a pull request.
> (Hope its OK, I am not used to pull requests to other orgs/repos)
> regards,
> Till

Once I'm at the office I'll review it and get back to you
